### ISSUE TITLE
UTXO Duplication 

### ISSUE THREAD

**Issue by Jossec101** [dgarage/NBXplorer#368] opened 2022-07-29 11:15 UTC
Hi there,

I'm getting duplicated UTXOs from a derivation scheme as follows:

```json
{
  "trackedSource": "DERIVATIONSCHEME:2-of-tpub1-tpub2-tpub3",
  "derivationStrategy": "2-of-tpub1-tpub2-tpub3",
  "currentHeight": 8469,
  "unconfirmed": {
    "utxOs": [],
    "spentOutpoints": []
  },
  "confirmed": {
    "utxOs": [
      {
        "feature": "Deposit",
        "outpoint": "73bad666d0dbfaf40c7b8e7706efbb01b2eaaa5cedbe5f82f411883444d5dc0b00000000",
        "index": 0,
        "transactionHash": "0bdcd544348811f4825fbeed5caaeab201bbef06778e7b0cf4fadbd066d6ba73",
        "scriptPubKey": "00209614d6c2b23b1a63b020401b36036c9b93a949a37aadcfaa8dc604dd1b1ac59d",
        "redeem": "5221022094238b674398076df0f8edd221d9fc2a63aea1ffc67799d22b0d477fda78be21022794926398642c6d54effbbdd290db2e40c8ef5594353d9e6d3d6a008b11aad72103afdcf962376fb534b87b5c0bd015c66132b0b46ea6087d0c613dc44f6040373553ae",
        "value": 2000000000,
        "keyPath": "0/7",
        "timestamp": 1658834458,
        "confirmations": 4410
      },
      {
        "feature": "Deposit",
        "outpoint": "73bad666d0dbfaf40c7b8e7706efbb01b2eaaa5cedbe5f82f411883444d5dc0b00000000",
        "index": 0,
        "transactionHash": "0bdcd544348811f4825fbeed5caaeab201bbef06778e7b0cf4fadbd066d6ba73",
        "scriptPubKey": "00209614d6c2b23b1a63b020401b36036c9b93a949a37aadcfaa8dc604dd1b1ac59d",
        "redeem": "5221022094238b674398076df0f8edd221d9fc2a63aea1ffc67799d22b0d477fda78be21022794926398642c6d54effbbdd290db2e40c8ef5594353d9e6d3d6a008b11aad72103afdcf962376fb534b87b5c0bd015c66132b0b46ea6087d0c613dc44f6040373553ae",
        "value": 2000000000,
        "keyPath": "0/7",
        "timestamp": 1658834458,
        "confirmations": 4410
      }
    ],
    "spentOutpoints": []
  }
}
```

I did wipe all the tx using /utxos/wipe and then /utxos/scan and it appeared again

**Comment by NicolasDorier** [comment] 2024-11-29 06:56
Closing this as it was in 2022, major refactoring happened since then, so I doubt it's still there. I couldn't reproduce either.

**Closed by NicolasDorier** 2024-11-29 06:56 UTC
