### ISSUE TITLE
Rescan of xpub key seems to fail after upgrading to bitcoin core version 0.19.0.1

### ISSUE THREAD

**Issue by lukeroberts** [dgarage/NBXplorer#229] opened 2019-12-30 01:28 UTC
I needed to rescan my wallet inside of btcpay server and it seems to fail now that I have upgraded to 0.19.0.1 with:

```
info: Explorer:       BTC: Start scanning xpub*REDACTED*-[p2sh] from index 0 with gap limit 10000, batch size 3000
info: Explorer:       BTC: Start scanning batch 0 of xpub*REDACTED*-[p2sh] from index 0
fail: Explorer:       BTC: Error while scanning xpub*REDACTED*-[p2sh]
NBitcoin.RPC.RPCException: scantxoutset "action" [scanobjects,...]

EXPERIMENTAL warning: this call may be removed or changed in future releases.

Scans the unspent transaction output set for entries that match certain output descriptors.
Examples of output descriptors are:
    addr(<address>)                      Outputs whose scriptPubKey corresponds to the specified address (does not include P2PK)
    raw(<hex script>)                    Outputs whose scriptPubKey equals the specified hex scripts
    combo(<pubkey>)                      P2PK, P2PKH, P2WPKH, and P2SH-P2WPKH outputs for the given pubkey
    pkh(<pubkey>)                        P2PKH outputs for the given pubkey
    sh(multi(<n>,<pubkey>,<pubkey>,...)) P2SH-multisig outputs for the given threshold and pubkeys

In the above, <pubkey> either refers to a fixed public key in hexadecimal notation, or to an xpub/xprv optionally followed by one
or more path elements separated by "/", and optionally ending in "/*" (unhardened), or "/*'" or "/*h" (hardened) to specify all
unhardened or hardened child keys.
In the latter case, a range needs to be specified by below if different from 1000.
For more information on output descriptors, see the documentation in the doc/descriptors.md file.

Arguments:
1. action                        (string, required) The action to execute
                                 "start" for starting a scan
                                 "abort" for aborting the current scan (returns true when abort was successful)
                                 "status" for progress report (in %) of the current scan
2. scanobjects                   (json array, required) Array of scan objects
                                 Every scan object is either a string descriptor or an object:
     [
       "descriptor",             (string) An output descriptor
       {                         (json object) An object with output descriptor and metadata
         "desc": "str",          (string, required) An output descriptor
         "range": n or [n,n],    (numeric or array, optional, default=1000) The range of HD chain indexes to explore (either end or [begin,end])
       },
       ...
     ]

Result:
{
  "success": true|false,         (boolean) Whether the scan was completed
  "txouts": n,                   (numeric) The number of unspent transaction outputs scanned
  "height": n,                   (numeric) The current block height (index)
  "bestblock": "hex",            (string) The hash of the block at the tip of the chain
  "unspents": [
   {
    "txid": "hash",              (string) The transaction id
    "vout": n,                   (numeric) The vout value
    "scriptPubKey": "script",    (string) The script key
    "desc": "descriptor",        (string) A specialized descriptor for the matched scriptPubKey
    "amount": x.xxx,             (numeric) The total amount in BTC of the unspent output
    "height": n,                 (numeric) Height of the unspent transaction output
   }
   ,...],
  "total_amount": x.xxx,          (numeric) The total amount of all found unspent outputs in BTC
]

   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.GetStatusScanTxoutSetAsync()
   at NBXplorer.ScanUTXOSetService.Listen() in C:\btcpayserver\NBXplorer\NBXplorer\ScanUTXOSetService.cs:line 163
```

I downgraded back to 0.18.1 and it worked as expected

**Comment by NicolasDorier** [comment] 2019-12-30 03:42
@lukeroberts interesting, they probably did a breaking change. I will have to find out what.

**Comment by NicolasDorier** [comment] 2020-01-12 13:21
mmmh I can't reproduce this on my regtest

**Comment by NicolasDorier** [comment] 2020-01-12 13:23
Can you try to run `scantxoutset status "[]"` via `bitcoin-cli.sh` ?

**Comment by NicolasDorier** [comment] 2020-01-12 13:27
Actually it has been fixed by @lontivero on https://github.com/MetacoSA/NBitcoin/commit/c08b637242d7555d1bd22a8219ad317d4b5cd921 

I will update NBitcoin for NBXplorer and it should fix the issue.

**Comment by NicolasDorier** [comment] 2020-01-12 13:31
Actually it should already be in a version with the commit above.
Can you try with latest version of nbx?

**Comment by NicolasDorier** [comment] 2020-01-12 13:50
Closing this, tried to run NBX test suite on 0.19.0.1 and did not get any issue.
Try on the latest version. Reopen if any issue.

**Closed by NicolasDorier** 2020-01-12 13:50 UTC
Labels: bug
