### ISSUE TITLE
why is the NBXplorer Server goes up to about 1GB RAM after a while?

### ISSUE THREAD

**Issue by bazooka70** [dgarage/NBXplorer#21] opened 2018-03-07 19:11 UTC
I have noticed that  NBXplorer Server goes up to about 1GB RAM and more after a while (can be a few minutes) and memory usage keeps climbing.
That is sometimes twice the RAM size used by Bitcoin Core...
Why is this really big memory footprint?
Is that an issue or am I just nagging again? :)

**Comment by NicolasDorier** [comment] 2018-03-07 19:14
No there is something wrong if it is going that big. I have not seen the issue on my side though.

**Comment by NicolasDorier** [comment] 2018-03-07 19:14
Is it synched?

**Comment by bazooka70** [comment] 2018-03-07 19:41
Yes

**Comment by NicolasDorier** [comment] 2018-03-07 21:06
@bazooka70 when you are not using NBXplorer and just letting it run without doing anything, does it still go up?

**Comment by bazooka70** [comment] 2018-03-08 11:03
I restarted the machine. run Bitcoin Core testnet - is consumes ~450MB at startup. then  run:
`start "" dotnet run --no-build -c Release -- --network=testnet`
It is just running....
The dotnet.exe process got up to 1.3GB in 5 min. I will monitor that process for a while whiteout sending requests to the server.

**Comment by NicolasDorier** [comment] 2018-03-08 13:06
@bazooka70 can you browse `v1/cryptos/BTC/status` ?

**Comment by bazooka70** [comment] 2018-03-08 15:15
`{"bitcoinStatus":{"blocks":1287720,"headers":1287720,"verificationProgress":0.99999126844586239,"isSynched":true,"incrementalRelayFee":1,"minRelayTxFee":1},"repositoryPingTime":0.00141,"isFullySynched":true,"chainHeight":1287720,"syncHeight":1287720,"chainType":"Test","cryptoCode":"BTC","supportedCryptoCodes":["BTC"],"version":"1.0.1.19"}`

**Comment by NicolasDorier** [comment] 2018-03-08 15:43
ok this is strange... updating my ndoes and monitoring that

**Comment by NicolasDorier** [comment] 2018-03-08 15:48
confirmed...

![image](https://user-images.githubusercontent.com/3020646/37160416-27bb7a46-22be-11e8-8afc-838627a50ebf.png)

Very strange, I am working on it. Thanks for the report.

**Comment by NicolasDorier** [comment] 2018-03-08 16:54
Ok so the problem is that there is a huge number of blocks in LTC+BTC, and I store the headers in memory.
I will try to limit this issue soon.

**Comment by NicolasDorier** [comment] 2018-03-08 18:57
Ok so I updated NBXplorer to .20

![image](https://user-images.githubusercontent.com/3020646/37170316-8c2bcc8c-22d8-11e8-9359-900f7d8452f2.png)

It is now a bit better. I can't do really more without major refactoring, so I am closing this issue.

**Comment by NicolasDorier** [comment] 2018-03-09 05:38
Reopening I think I have a way to reduce from 800MB to 100MB. Will try tomorrow.

**Comment by bazooka70** [comment] 2018-03-09 06:48
What is the cost of the memory reduction? will there be a performance cost or other?
BTW, I'm only supporting btc. i.e. `chains=btc`

**Comment by NicolasDorier** [comment] 2018-03-11 01:47
Updated, note you will see that only after the second reboot. (Wait the start of nodes is finished, then restart)

![image](https://user-images.githubusercontent.com/3020646/37248590-7d7208d0-2519-11e8-8c3f-e8191191343f.png)

**Comment by NicolasDorier** [comment] 2018-03-11 01:47
Can't get more than that :(

**Closed by NicolasDorier** 2018-03-11 01:47 UTC

**Comment by bazooka70** [comment] 2018-03-11 06:41
Well done! the process got down to ~750M now. when it was about 1.4G
:+1:

**Comment by NicolasDorier** [comment] 2018-03-12 03:55
If you restart once again I think you might go to 500 something.
