### ISSUE TITLE
Is there a way to control amount of memory used?

### ISSUE THREAD

**Issue by duckartes** [dgarage/NBXplorer#143] opened 2018-12-11 20:22 UTC
This would be useful for testing on low memory systems (Raspberry Pi, etc.)

**Comment by NicolasDorier** [comment] 2018-12-12 03:17
The amount of memory used is proportional to the number of blocks in the chain. Chains like DOGE or VIA who has lots of block will take more memory.

It is theorically a solvable problem, but would involve some heavy refactoring. Started thinking about it, and not found a good solution yet.

**Comment by NicolasDorier** [comment] 2018-12-12 03:34
I am testing on raspberry pi and don't have this problem, how much RAM it takes?

**Comment by NicolasDorier** [comment] 2018-12-12 03:36
can you check `ps aux --sort -rss` ?

**Comment by duckartes** [comment] 2018-12-12 03:37
Do you run default configuration and have you ever had it catch back up after a couple days of being out of sync? 

I'm syncing bitcoind back up and I'll run it to verify again.

**Comment by NicolasDorier** [comment] 2018-12-12 03:39
Normally when your node catch up, NBXplorer should be inactive. NBXplorer starts its work only when the node is fully synched.

**Comment by duckartes** [comment] 2018-12-12 03:40
Clarification: NBXplorer being offline for a few days.

**Comment by duckartes** [comment] 2018-12-12 03:45
ps aux --sort -rss | grep dotnet
```

pi       20989 97.4 76.6 1463808 766800 pts/2  SLl+ 03:38   6:29 dotnet exec /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll
pi       20777  2.4  0.4 223812  4736 pts/2    SLl+ 03:38   0:10 dotnet run --no-launch-profile --no-build -c Release -p NBXplorer/NBXplorer.csproj --

```

Is this enough information?

**Comment by NicolasDorier** [comment] 2018-12-12 04:05
This are the tops?

**Comment by NicolasDorier** [comment] 2018-12-12 04:07
do you have any interesting logs in NBX? Do you support only Bitcoin on Mainnet on it?

**Comment by NicolasDorier** [comment] 2018-12-12 04:07
It should not take that much memory

**Comment by duckartes** [comment] 2018-12-12 04:16
Bitcoin mainnet only. It filled up the RAM and my 2G swap was about 30% full. 

Is there a default log location? I can't seem to find one. 

Just testing so I'll clear the NBXplorer directory and try to replicate.

**Comment by duckartes** [comment] 2018-12-12 04:50
pi@raspberrypi:/mnt/pidrive/.src/github.com/dgarage/NBxplorer$ ./build.sh 
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 1.32 sec for /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer.Client/NBXplorer.Client.csproj.
  Restore completed in 1.65 sec for /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/NBXplorer.csproj.
  NBXplorer.Client -> /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer.Client/bin/Release/netstandard2.0/NBXplorer.Client.dll
  NBXplorer -> /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:02:14.05
```

pi@raspberrypi:/mnt/pidrive/.src/github.com/dgarage/NBxplorer$ ./run.sh 
```
info: Configuration:  Data Directory: /home/pi/.nbxplorer/Main
info: Configuration:  Configuration File: /home/pi/.nbxplorer/Main/settings.config
info: Configuration:  Creating configuration file
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://localhost:8332/
Hosting environment: Production
Content root path: /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/
Now listening on: http://127.0.0.1:24444
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: RPC connection successfull
info: Configuration:  BTC: Full node version detected: 179900
info: Configuration:  BTC: Loading chain from node (127.0.0.1:8333)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 553483
info: Configuration:  BTC: Saving chain to cache...
info: Configuration:  BTC: Chain cached
info: Explorer:       BTC: Handshaked node
info: Explorer:       BTC: Starting scan at block 553483
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
```
ps aux --sort -rss | grep dotnet
```
pi       10530 28.8 19.9 639720 199156 pts/3   SLl+ 04:45   0:52 dotnet exec /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll                                     
pi       10406  5.3  6.5 223872 65624 pts/3    SLl+ 04:45   0:10 dotnet run --no-launch-profile --no-build -c Release -p NBXplorer/NBXplorer.csproj --     
```


I'll leave it off now for a day or two and report back.

**Comment by NicolasDorier** [comment] 2018-12-12 08:13
let me know my raspberry now:

```
999      18496  3.3 31.8 497320 302236 ?       SLsl Dec04 384:30 bitcoind
root     18960  4.6 19.3 893168 183312 ?       Ssl  Dec04 534:14 lnd
root     10825  0.2  8.8 642568 84144 ?        SLsl Dec05  23:00 dotnet NBXplorer.dll
```

**Comment by NicolasDorier** [comment] 2018-12-13 12:51
@corbelantoine you are using `startheight=0` ? if you don't, you have no issue?

**Comment by corbelantoine** [comment] 2018-12-13 12:53
Yes I’m using startheight=0
No I don’t have any issue when I don’t because it finishes instantly to sync.

**Comment by duckartes** [comment] 2018-12-13 15:52
./run.sh
```
info: Configuration:  Data Directory: /home/pi/.nbxplorer/Main
info: Configuration:  Configuration File: /home/pi/.nbxplorer/Main/settings.config
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  Network: Mainnet
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Testing RPC connection to http://localhost:8332/
Hosting environment: Production
Content root path: /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/
Now listening on: http://127.0.0.1:24444
Application started. Press Ctrl+C to shut down.
info: Configuration:  BTC: RPC connection successfull
info: Configuration:  BTC: Full node version detected: 179900
info: Configuration:  BTC: Loading chain from cache...
info: Configuration:  BTC: Height: 553483
info: Configuration:  BTC: Loading chain from node (127.0.0.1:8333)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 553657
info: Configuration:  BTC: Saving chain to cache...
info: Configuration:  BTC: Chain cached
info: Explorer:       BTC: Handshaked node
info: Explorer:       BTC: Starting scan at block 553657
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
info: Events:         BTC: Node state changed: NBXplorerSynching => Ready
info: Events:         BTC: New block 00000000000000000018838f2cc055592cdbec9ac3c0e555c07bbb31f9bc0291 (553658)                                                                                                    
info: Events:         BTC: New block 00000000000000000029ee916c2a09e93bc2b4f830281d14cbebb2695e9552ee (553659)
```

No issues on this run, but I think my issue was related to @corbelantoine: 

This time the scan started at BTC: Height: 553657, and not from where I previously shut the server off at BTC: Height: 553483.

In the past it has synced many more blocks than this when I started the server after a period of time of being off.

**Comment by duckartes** [comment] 2018-12-13 15:54
I'll leave it off for another extended period of time and report back.

**Comment by NicolasDorier** [comment] 2018-12-14 05:52
I think I know the problem.
I may download the blocks too fast, while the DB try to catch up.

**Comment by NicolasDorier** [comment] 2018-12-14 10:00
Ok I don't know how to reproduce the problem yet, but I could reproduce this issue. Trying to find a way to fix this.

**Comment by NicolasDorier** [comment] 2018-12-14 10:16
Can you try with the latest version? I am trying to resurrect my raspberri

**Comment by NicolasDorier** [comment] 2018-12-14 10:47
2.0.0.4

**Comment by NicolasDorier** [comment] 2018-12-14 10:57
mmh in 2.0.0.4 it just blocks.

**Comment by NicolasDorier** [comment] 2018-12-14 15:02
Ok 2.0.0.7 should fix it for good. Can you try?

**Comment by AntoineXBTO** [comment] 2018-12-14 15:07
Trying now, getting back to you in 1h

**Comment by AntoineXBTO** [comment] 2018-12-14 15:11
It sounds like it works! Memory is stable around a decent level, sync is being done (logs are ok) and SSD size is increasing.
Well done!

**Comment by NicolasDorier** [comment] 2018-12-14 15:49
cool! Closing this, please reopen if you see anything strange.

**Comment by NicolasDorier** [comment] 2018-12-14 15:50
@AntoineXBTO for information, how much time it takes to process 1 blocks?

**Closed by NicolasDorier** 2018-12-14 15:49 UTC

**Comment by AntoineXBTO** [comment] 2018-12-14 15:51
Around block 208k:
![image](https://user-images.githubusercontent.com/40615019/50013062-2a9a6300-ff8e-11e8-8ae6-5618f4464461.png)

**Comment by AntoineXBTO** [comment] 2018-12-14 15:53
![image](https://user-images.githubusercontent.com/40615019/50013182-7c42ed80-ff8e-11e8-8122-5e06c865311a.png)

**Comment by duckartes** [comment] 2018-12-15 04:53
Excellent. 

ps aux --sort -rss | grep dotnet
```
pi        7963  145 27.5 740944 275488 pts/1   SLl+ 04:47   5:45 dotnet exec /mnt/pidrive/.src/github.com/dgarage/NBxplorer/NBXplorer/bin/Release/netcoreapp2.1/NBXplorer.dll
pi        7825  3.9  6.1 215704 61360 pts/1    SLl+ 04:46   0:09 dotnet run --no-launch-profile --no-build -c Release -p NBXplorer/NBXplorer.csproj --
```



Never rose above 65% memory usage (system total) while catching up since my last post. 

:+1:

**Comment by NicolasDorier** [comment] 2018-12-15 12:01
Great, thanks all for helping fixing that!

**Comment by NicolasDorier** [comment] 2018-12-15 12:13
@AntoineXBTO just a note: You should not have to rescan stuff with NBX, except if you know what you do.
If your goal is to recover a wallet, you don't have to rescan all the blocks, you can just use the scan utxo set feature.

**Comment by corbelantoine** [comment] 2018-12-15 16:53
Thanks.
But I don’t know in advance which wallet I’m going to need...

**Comment by NicolasDorier** [comment] 2018-12-16 06:48
@corbelantoine the full rescan is ONLY useful if you are already tracking something.
NBXplorer does on save any data (outside of new block events) if you don't track anything.

**Comment by NicolasDorier** [comment] 2018-12-16 06:49
You can't ask to NBXPlorer to index all the blockchain so that you can have the balance of arbitrary `xpub`.
